language: go
go:
  - 1.x

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE task;'

script:
  - GOMAXPROCS=4 go test ./ -v
  - GOMAXPROCS=4 go test ./repository -v
  - go test ./sender_service -v
  - go test ./task_manager -v
  - go test ./error_service -v
  - go test ./prioritized_task_list -v
  - go test ./preloader_service -v
  - go test ./monitoring_service -v
  - go test ./waiting_service -v

notifications:
  email: false